name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install buf
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.24.0
        with:
          version: 1.47.2
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: format
        run: make check-fmt

      - name: lint
        run: make lint

      - name: check-breaking
        run: make check-breaking
