name: Generate Protobuf Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: '1.21'

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install protoc-gen-doc
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH
          export PATH="$HOME/go/bin:$PATH"

      - name: Generate documentation.json
        run: |
          export PATH="$HOME/go/bin:$PATH"
      
          PROTO_FILES=$(find ./proto -name "*.proto")
          
          mkdir gen-docs
      
          protoc \
            --plugin=protoc-gen-doc=$HOME/go/bin/protoc-gen-doc \
            --proto_path=./proto \
            --doc_out=json,documentation.json:./gen-docs \
            $PROTO_FILES

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gen-docs
          publish_dir: ./gen-docs
          force_orphan: true
